definitions:
  models.DepositRequest:
    properties:
      amount:
        minimum: 0
        type: number
      customer_id:
        minLength: 1
        type: string
      details:
        additionalProperties:
          type: string
        type: object
      gateway_id:
        minLength: 1
        type: string
    required:
    - customer_id
    - gateway_id
    type: object
  models.DepositResponse:
    properties:
      status:
        type: string
      transaction_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/deposit:
    post:
      consumes:
      - application/json
      description: This will deposit a specific amount into a user's account using
        a payment gateway.
      parameters:
      - description: Deposit Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.DepositRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DepositResponse'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Deposit money into an account
      tags:
      - Deposits
swagger: "2.0"
